// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3UZgOFEosxWdWoiZpsbUYoaBPgXyNxDA',
    appId: '1:781761200912:web:2bd68fa03ba96fdaccdb95',
    messagingSenderId: '781761200912',
    projectId: 'chatting-app-829cc',
    authDomain: 'chatting-app-829cc.firebaseapp.com',
    storageBucket: 'chatting-app-829cc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCidWCR9QKdrMa_bTALgZZqqEwLEHSRzRY',
    appId: '1:781761200912:android:00fc85debfe83088ccdb95',
    messagingSenderId: '781761200912',
    projectId: 'chatting-app-829cc',
    storageBucket: 'chatting-app-829cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgI_2stySM68fcURwiTargDOvb7Aa-BoI',
    appId: '1:781761200912:ios:99611cc3b3734ca0ccdb95',
    messagingSenderId: '781761200912',
    projectId: 'chatting-app-829cc',
    storageBucket: 'chatting-app-829cc.appspot.com',
    iosBundleId: 'com.example.rollDice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgI_2stySM68fcURwiTargDOvb7Aa-BoI',
    appId: '1:781761200912:ios:f89a1dc1cf424427ccdb95',
    messagingSenderId: '781761200912',
    projectId: 'chatting-app-829cc',
    storageBucket: 'chatting-app-829cc.appspot.com',
    iosBundleId: 'com.example.rollDice.RunnerTests',
  );
}
